language: php

sudo: false

php:
  - 5.5
  - 5.6

env:
  matrix:
    - DB=PGSQL

before_script:
 - composer self-update || true
 - phpenv rehash
 - COMPOSER_ROOT_VERSION=2.0.x-dev composer install --prefer-dist

script:
 - vendor/bin/phpunit
